### PR TITLE
clarify certificate arn parameter

### PR DESCRIPTION
**Pull request by cat5inthecradle**

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
@kmcgill88 please review

**Comment by cat5inthecradle** [comment]
@kmcgill88 have you had a chance to look at this yet?

**Comment by cat5inthecradle** [comment]
@kmcgill88 please review, i need that OSS cred

**Comment by cat5inthecradle** [comment]
bump

**Comment by cat5inthecradle** [comment]
bump

**Comment by cat5inthecradle** [comment]
opps sorry did not mean to dupe post

**Review by kmcgill88 — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
👍👍👍👍👍 💯

**Pull request merged**
